### PR TITLE
Update oauth2 dependency, allow redirect_uri to be set.

### PR DESCRIPTION
**Pull request by patrickdavey**
Hi there,

Thanks for creating the classlink strategy. I was trying to use it with a Rails 5 project and was unable to install it, because of the reliance on version `1.1.1` of `omniauth-oauth2`. I've updated it to 1.4.

I also wanted to be able to set the `redirect_uri` to a custom uri, for testing in development. This just tweaks the `callback_url` to allow the settings to be used.

It would be _great_ if you could accept this PR and push out a new version of the gem.

Thanks!
Patrick

### CODE REVIEW

**Comment by patrickdavey** [comment]
I also tweaked the readme, if you have the provider as `classlink`, it looks for the `Classlink` class, this gem uses `ClassLink`, so the provider needs to be passed as `class_link` :)

**Comment by kamilbednarz** [comment]
Hey @patrickdavey , I'd like to make a couple of tweaks before I merge it in.

You can see them in my PR to your repo:
https://github.com/patrickdavey/omniauth-classlink/pull/1

**Comment by patrickdavey** [comment]
hi @kamilbednarz , this PR now contains just the changes we worked through on my fork.

Once this is merged in I'll open a PR for the `uid` and option changes and we can work through whether those are worth merging.

Thanks heaps for maintaining the gem :)

**Review by kamilbednarz — APPROVED** [review]

**Comment by kamilbednarz** [comment]
Thanks Patrick, 0.2.0 is available in rubygems.

**Comment by patrickdavey** [comment]
Excellent thanks, I'll open a PR for the uid too, as that seems useful. I did also take out the options (which was partly me messing around, they didn't seem to _do anything_, but, I'll double check that)

Thanks for the release!

**Pull request merged**
